# Build is responsible for testing builds on all supported platforms.
# It is broken up into three separate jobs with targeted builds so that each OS will
# build in parallel and speed up overall CI time.
name: Build
on:
  workflow_dispatch:
  pull_request:

jobs:
  build_linux:
    runs-on: mkelly-runner
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Build
        run: make build-linux
      - name: Scan Third Party Dependency Licenses
        run: |
          go install github.com/uw-labs/lichen@v0.1.7
          lichen --config=./license.yaml $(find dist/collector_* dist/updater_*)
  build_darwin:
    runs-on: self-hosted
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Build
        run: make build-darwin
      - name: Scan Third Party Dependency Licenses
        run: |
          go install github.com/uw-labs/lichen@v0.1.7
          lichen --config=./license.yaml $(find dist/collector_* dist/updater_*)
